<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USMUMKAMADAN3" ignored="0" name="ExampleTest" tests="5" failures="1" timestamp="16 Jul 2018 12:17:21 GMT" time="23.782" errors="0">
  <testcase name="DemoQA" time="6.94" classname="Flows.LoginLogout"/>
  <testcase name="DemoQARegister" time="12.365" classname="Flows.LoginLogout"/>
  <testcase name="FirstTestCase" time="0.131" classname="Flows.LoginLogout2">
    <failure type="java.lang.AssertionError" message="Assertion Inside Catch expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Inside Catch expected [true] but found [false]
at Keywords.KeywordRepository.loadURL(KeywordRepository.java:104)
at Flows.LoginLogout2.FirstTestCase(LoginLogout2.java:26)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- FirstTestCase -->
  <testcase name="SecondTestCase" time="0.0" classname="Flows.LoginLogout2"/>
  <testcase name="ThirdTestCase" time="0.0" classname="Flows.LoginLogout2"/>
</testsuite> <!-- ExampleTest -->
