<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MADANK-W01" name="Flows.LoginLogout2" tests="1" failures="0" timestamp="15 Oct 2018 10:09:00 GMT" time="46.267" errors="1">
  <testcase name="FirstTestCase" time="46.267" classname="Flows.LoginLogout2">
    <error type="org.sikuli.script.FindFailed" message="C:/Users/madank/Documents/GitHub/cso-automation/resources/LoginScreen_Bench.png: (354x265) in R[783,389 354x262]@S(0) E:Y, T:30.0">
      <![CDATA[FindFailed: C:/Users/madank/Documents/GitHub/cso-automation/resources/LoginScreen_Bench.png: (354x265) in R[783,389 354x262]@S(0) E:Y, T:30.0
  Line 2782, in file Region.java

at org.sikuli.script.Region.wait(Region.java:2782)
at org.sikuli.script.Region.wait(Region.java:2729)
at Flows.LoginLogout2.FirstTestCase(LoginLogout2.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- FirstTestCase -->
</testsuite> <!-- Flows.LoginLogout2 -->
